import pycountry

# Note if 2 countries have the same denonym, the country with higher population is used.
denonym_list = {"Afghan": {"numeric": "4", "alpha_2": "AF", "alpha_3": "AFG", "country": "Afghanistan"},
                "Åland Island": {"numeric": "248", "alpha_2": "AX", "alpha_3": "ALA", "country": "Åland Islands"},
                "Albanian": {"numeric": "8", "alpha_2": "AL", "alpha_3": "ALB", "country": "Albania"},
                "Algerian": {"numeric": "12", "alpha_2": "DZ", "alpha_3": "DZA", "country": "Algeria"},
                "American Samoan": {"numeric": "16", "alpha_2": "AS", "alpha_3": "ASM", "country": "American Samoa"},
                "Andorran": {"numeric": "20", "alpha_2": "AD", "alpha_3": "AND", "country": "Andorra"},
                "Angolan": {"numeric": "24", "alpha_2": "AO", "alpha_3": "AGO", "country": "Angola"},
                "Anguillan": {"numeric": "660", "alpha_2": "AI", "alpha_3": "AIA", "country": "Anguilla"},
                "Antarctic": {"numeric": "10", "alpha_2": "AQ", "alpha_3": "ATA", "country": "Antarctica"},
                "Antiguan": {"numeric": "28", "alpha_2": "AG", "alpha_3": "ATG", "country": "Antigua and Barbuda"},
                "Barbudan": {"numeric": "28", "alpha_2": "AG", "alpha_3": "ATG", "country": "Antigua and Barbuda"},
                "Argentine": {"numeric": "32", "alpha_2": "AR", "alpha_3": "ARG", "country": "Argentina"},
                "Armenian": {"numeric": "51", "alpha_2": "AM", "alpha_3": "ARM", "country": "Armenia"},
                "Aruban": {"numeric": "533", "alpha_2": "AW", "alpha_3": "ABW", "country": "Aruba"},
                "Australian": {"numeric": "36", "alpha_2": "AU", "alpha_3": "AUS", "country": "Australia"},
                "Austrian": {"numeric": "40", "alpha_2": "AT", "alpha_3": "AUT", "country": "Austria"},
                "Azerbaijani": {"numeric": "31", "alpha_2": "AZ", "alpha_3": "AZE", "country": "Azerbaijan"},
                "Azeri": {"numeric": "31", "alpha_2": "AZ", "alpha_3": "AZE", "country": "Azerbaijan"},
                "Bahamian": {"numeric": "44", "alpha_2": "BS", "alpha_3": "BHS", "country": "Bahamas"},
                "Bahraini": {"numeric": "48", "alpha_2": "BH", "alpha_3": "BHR", "country": "Bahrain"},
                "Bangladeshi": {"numeric": "50", "alpha_2": "BD", "alpha_3": "BGD", "country": "Bangladesh"},
                "Barbadian": {"numeric": "52", "alpha_2": "BB", "alpha_3": "BRB", "country": "Barbados"},
                "Belarusian": {"numeric": "112", "alpha_2": "BY", "alpha_3": "BLR", "country": "Belarus"},
                "Belgian": {"numeric": "56", "alpha_2": "BE", "alpha_3": "BEL", "country": "Belgium"},
                "Belizean": {"numeric": "84", "alpha_2": "BZ", "alpha_3": "BLZ", "country": "Belize"},
                "Beninese": {"numeric": "204", "alpha_2": "BJ", "alpha_3": "BEN", "country": "Benin"},
                "Beninois": {"numeric": "204", "alpha_2": "BJ", "alpha_3": "BEN", "country": "Benin"},
                "Bermudian": {"numeric": "60", "alpha_2": "BM", "alpha_3": "BMU", "country": "Bermuda"},
                "Bermudan": {"numeric": "60", "alpha_2": "BM", "alpha_3": "BMU", "country": "Bermuda"},
                "Bhutanese": {"numeric": "64", "alpha_2": "BT", "alpha_3": "BTN", "country": "Bhutan"},
                "Bolivian": {"numeric": "68", "alpha_2": "BO", "alpha_3": "BOL",
                             "country": "Bolivia, Plurinational State of"},
                "Bonaire": {"numeric": "535", "alpha_2": "BQ", "alpha_3": "BES",
                            "country": "Bonaire, Sint Eustatius and Saba"},
                "Bosnian": {"numeric": "70", "alpha_2": "BA", "alpha_3": "BIH", "country": "Bosnia and Herzegovina"},
                "Herzegovinian": {"numeric": "70", "alpha_2": "BA", "alpha_3": "BIH",
                                  "country": "Bosnia and Herzegovina"},
                "Motswana": {"numeric": "72", "alpha_2": "BW", "alpha_3": "BWA", "country": "Botswana"},
                "Botswanan": {"numeric": "72", "alpha_2": "BW", "alpha_3": "BWA", "country": "Botswana"},
                "Bouvet Island": {"numeric": "74", "alpha_2": "BV", "alpha_3": "BVT", "country": "Bouvet Island"},
                "Brazilian": {"numeric": "76", "alpha_2": "BR", "alpha_3": "BRA", "country": "Brazil"},
                "BIOT": {"numeric": "86", "alpha_2": "IO", "alpha_3": "IOT",
                         "country": "British Indian Ocean Territory"},
                "Bruneian": {"numeric": "96", "alpha_2": "BN", "alpha_3": "BRN", "country": "Brunei Darussalam"},
                "Bulgarian": {"numeric": "100", "alpha_2": "BG", "alpha_3": "BGR", "country": "Bulgaria"},
                "Burkinabé": {"numeric": "854", "alpha_2": "BF", "alpha_3": "BFA", "country": "Burkina Faso"},
                "Burundian": {"numeric": "108", "alpha_2": "BI", "alpha_3": "BDI", "country": "Burundi"},
                "Cabo Verdean": {"numeric": "132", "alpha_2": "CV", "alpha_3": "CPV", "country": "Cabo Verde"},
                "Cambodian": {"numeric": "116", "alpha_2": "KH", "alpha_3": "KHM", "country": "Cambodia"},
                "Cameroonian": {"numeric": "120", "alpha_2": "CM", "alpha_3": "CMR", "country": "Cameroon"},
                "Canadian": {"numeric": "124", "alpha_2": "CA", "alpha_3": "CAN", "country": "Canada"},
                "Caymanian": {"numeric": "136", "alpha_2": "KY", "alpha_3": "CYM", "country": "Cayman Islands"},
                "Central African": {"numeric": "140", "alpha_2": "CF", "alpha_3": "CAF",
                                    "country": "Central African Republic"},
                "Chadian": {"numeric": "148", "alpha_2": "TD", "alpha_3": "TCD", "country": "Chad"},
                "Chilean": {"numeric": "152", "alpha_2": "CL", "alpha_3": "CHL", "country": "Chile"},
                "Chinese": {"numeric": "156", "alpha_2": "CN", "alpha_3": "CHN", "country": "China"},
                "Christmas Island": {"numeric": "162", "alpha_2": "CX", "alpha_3": "CXR",
                                     "country": "Christmas Island"},
                "Cocos Island": {"numeric": "166", "alpha_2": "CC", "alpha_3": "CCK",
                                 "country": "Cocos (Keeling) Islands"},
                "Colombian": {"numeric": "170", "alpha_2": "CO", "alpha_3": "COL", "country": "Colombia"},
                "Comoran": {"numeric": "174", "alpha_2": "KM", "alpha_3": "COM", "country": "Comoros"},
                "Comorian": {"numeric": "174", "alpha_2": "KM", "alpha_3": "COM", "country": "Comoros"},
                "Congolese": {"numeric": "180", "alpha_2": "CD", "alpha_3": "COD",
                              "country": "Congo, The Democratic Republic of the"},
                "Cook Island": {"numeric": "184", "alpha_2": "CK", "alpha_3": "COK", "country": "Cook Islands"},
                "Costa Rican": {"numeric": "188", "alpha_2": "CR", "alpha_3": "CRI", "country": "Costa Rica"},
                "Ivorian": {"numeric": "384", "alpha_2": "CI", "alpha_3": "CIV", "country": "Côte d'Ivoire"},
                "Croatian": {"numeric": "191", "alpha_2": "HR", "alpha_3": "HRV", "country": "Croatia"},
                "Cuban": {"numeric": "192", "alpha_2": "CU", "alpha_3": "CUB", "country": "Cuba"},
                "Curaçaoan": {"numeric": "531", "alpha_2": "CW", "alpha_3": "CUW", "country": "Curaçao"},
                "Cypriot": {"numeric": "196", "alpha_2": "CY", "alpha_3": "CYP", "country": "Cyprus"},
                "Czech": {"numeric": "203", "alpha_2": "CZ", "alpha_3": "CZE", "country": "Czech Republic"},
                "Danish": {"numeric": "208", "alpha_2": "DK", "alpha_3": "DNK", "country": "Denmark"},
                "Djiboutian": {"numeric": "262", "alpha_2": "DJ", "alpha_3": "DJI", "country": "Djibouti"},
                "Dominican": {"numeric": "214", "alpha_2": "DO", "alpha_3": "DOM", "country": "Dominican Republic"},
                "Ecuadorian": {"numeric": "218", "alpha_2": "EC", "alpha_3": "ECU", "country": "Ecuador"},
                "Egyptian": {"numeric": "818", "alpha_2": "EG", "alpha_3": "EGY", "country": "Egypt"},
                "Salvadoran": {"numeric": "222", "alpha_2": "SV", "alpha_3": "SLV", "country": "El Salvador"},
                "Equatorial Guinean": {"numeric": "226", "alpha_2": "GQ", "alpha_3": "GNQ",
                                       "country": "Equatorial Guinea"},
                "Equatoguinean": {"numeric": "226", "alpha_2": "GQ", "alpha_3": "GNQ", "country": "Equatorial Guinea"},
                "Eritrean": {"numeric": "232", "alpha_2": "ER", "alpha_3": "ERI", "country": "Eritrea"},
                "Estonian": {"numeric": "233", "alpha_2": "EE", "alpha_3": "EST", "country": "Estonia"},
                "Ethiopian": {"numeric": "231", "alpha_2": "ET", "alpha_3": "ETH", "country": "Ethiopia"},
                "Falkland Island": {"numeric": "238", "alpha_2": "FK", "alpha_3": "FLK",
                                    "country": "Falkland Islands (Malvinas)"},
                "Faroese": {"numeric": "234", "alpha_2": "FO", "alpha_3": "FRO", "country": "Faroe Islands"},
                "Fijian": {"numeric": "242", "alpha_2": "FJ", "alpha_3": "FJI", "country": "Fiji"},
                "Finnish": {"numeric": "246", "alpha_2": "FI", "alpha_3": "FIN", "country": "Finland"},
                "French": {"numeric": "250", "alpha_2": "FR", "alpha_3": "FRA", "country": "France"},
                "French Guianese": {"numeric": "254", "alpha_2": "GF", "alpha_3": "GUF", "country": "French Guiana"},
                "French Polynesian": {"numeric": "258", "alpha_2": "PF", "alpha_3": "PYF",
                                      "country": "French Polynesia"},
                "French Southern Territories": {"numeric": "260", "alpha_2": "TF", "alpha_3": "ATF",
                                                "country": "French Southern Territories"},
                "Gabonese": {"numeric": "266", "alpha_2": "GA", "alpha_3": "GAB", "country": "Gabon"},
                "Gambian": {"numeric": "270", "alpha_2": "GM", "alpha_3": "GMB", "country": "Gambia"},
                "Georgian": {"numeric": "268", "alpha_2": "GE", "alpha_3": "GEO", "country": "Georgia"},
                "German": {"numeric": "276", "alpha_2": "DE", "alpha_3": "DEU", "country": "Germany"},
                "Ghanaian": {"numeric": "288", "alpha_2": "GH", "alpha_3": "GHA", "country": "Ghana"},
                "Gibraltar": {"numeric": "292", "alpha_2": "GI", "alpha_3": "GIB", "country": "Gibraltar"},
                "Greek": {"numeric": "300", "alpha_2": "GR", "alpha_3": "GRC", "country": "Greece"},
                "Hellenic": {"numeric": "300", "alpha_2": "GR", "alpha_3": "GRC", "country": "Greece"},
                "Greenlandic": {"numeric": "304", "alpha_2": "GL", "alpha_3": "GRL", "country": "Greenland"},
                "Grenadian": {"numeric": "308", "alpha_2": "GD", "alpha_3": "GRD", "country": "Grenada"},
                "Guadeloupe": {"numeric": "312", "alpha_2": "GP", "alpha_3": "GLP", "country": "Guadeloupe"},
                "Guamanian": {"numeric": "316", "alpha_2": "GU", "alpha_3": "GUM", "country": "Guam"},
                "Guambat": {"numeric": "316", "alpha_2": "GU", "alpha_3": "GUM", "country": "Guam"},
                "Guatemalan": {"numeric": "320", "alpha_2": "GT", "alpha_3": "GTM", "country": "Guatemala"},
                "Guinean": {"numeric": "324", "alpha_2": "GN", "alpha_3": "GIN", "country": "Guinea"},
                "Bissau-Guinean": {"numeric": "624", "alpha_2": "GW", "alpha_3": "GNB", "country": "Guinea-Bissau"},
                "Guyanese": {"numeric": "328", "alpha_2": "GY", "alpha_3": "GUY", "country": "Guyana"},
                "Haitian": {"numeric": "332", "alpha_2": "HT", "alpha_3": "HTI", "country": "Haiti"},
                "Heard Island": {"numeric": "334", "alpha_2": "HM", "alpha_3": "HMD",
                                 "country": "Heard Island and McDonald Islands"},
                "McDonald Islands": {"numeric": "334", "alpha_2": "HM", "alpha_3": "HMD",
                                     "country": "Heard Island and McDonald Islands"},
                "Vatican": {"numeric": "336", "alpha_2": "VA", "alpha_3": "VAT",
                            "country": "Holy See (Vatican City State)"},
                "Honduran": {"numeric": "340", "alpha_2": "HN", "alpha_3": "HND", "country": "Honduras"},
                "Hong Kong": {"numeric": "344", "alpha_2": "HK", "alpha_3": "HKG", "country": "Hong Kong"},
                "Hong Kongese": {"numeric": "344", "alpha_2": "HK", "alpha_3": "HKG", "country": "Hong Kong"},
                "Hungarian": {"numeric": "348", "alpha_2": "HU", "alpha_3": "HUN", "country": "Hungary"},
                "Magyar": {"numeric": "348", "alpha_2": "HU", "alpha_3": "HUN", "country": "Hungary"},
                "Icelandic": {"numeric": "352", "alpha_2": "IS", "alpha_3": "ISL", "country": "Iceland"},
                "Indian": {"numeric": "356", "alpha_2": "IN", "alpha_3": "IND", "country": "India"},
                "Indonesian": {"numeric": "360", "alpha_2": "ID", "alpha_3": "IDN", "country": "Indonesia"},
                "Iranian": {"numeric": "364", "alpha_2": "IR", "alpha_3": "IRN",
                            "country": "Iran, Islamic Republic of"},
                "Persian": {"numeric": "364", "alpha_2": "IR", "alpha_3": "IRN",
                            "country": "Iran, Islamic Republic of"},
                "Iraqi": {"numeric": "368", "alpha_2": "IQ", "alpha_3": "IRQ", "country": "Iraq"},
                "Irish": {"numeric": "372", "alpha_2": "IE", "alpha_3": "IRL", "country": "Ireland"},
                "Manx": {"numeric": "833", "alpha_2": "IM", "alpha_3": "IMN", "country": "Isle of Man"},
                "Israeli": {"numeric": "376", "alpha_2": "IL", "alpha_3": "ISR", "country": "Israel"},
                "Italian": {"numeric": "380", "alpha_2": "IT", "alpha_3": "ITA", "country": "Italy"},
                "Jamaican": {"numeric": "388", "alpha_2": "JM", "alpha_3": "JAM", "country": "Jamaica"},
                "Japanese": {"numeric": "392", "alpha_2": "JP", "alpha_3": "JPN", "country": "Japan"},
                "Channel Island": {"numeric": "832", "alpha_2": "JE", "alpha_3": "JEY", "country": "Jersey"},
                "Jordanian": {"numeric": "400", "alpha_2": "JO", "alpha_3": "JOR", "country": "Jordan"},
                "Kazakhstani": {"numeric": "398", "alpha_2": "KZ", "alpha_3": "KAZ", "country": "Kazakhstan"},
                "Kazakh": {"numeric": "398", "alpha_2": "KZ", "alpha_3": "KAZ", "country": "Kazakhstan"},
                "Kenyan": {"numeric": "404", "alpha_2": "KE", "alpha_3": "KEN", "country": "Kenya"},
                "I-Kiribati": {"numeric": "296", "alpha_2": "KI", "alpha_3": "KIR", "country": "Kiribati"},
                "North Korean": {"numeric": "408", "alpha_2": "KP", "alpha_3": "PRK",
                                 "country": "Korea, Democratic People's Republic of"},
                "South Korean": {"numeric": "410", "alpha_2": "KR", "alpha_3": "KOR", "country": "Korea, Republic of"},
                "Kuwaiti": {"numeric": "414", "alpha_2": "KW", "alpha_3": "KWT", "country": "Kuwait"},
                "Kyrgyzstani": {"numeric": "417", "alpha_2": "KG", "alpha_3": "KGZ", "country": "Kyrgyzstan"},
                "Kyrgyz": {"numeric": "417", "alpha_2": "KG", "alpha_3": "KGZ", "country": "Kyrgyzstan"},
                "Kirgiz": {"numeric": "417", "alpha_2": "KG", "alpha_3": "KGZ", "country": "Kyrgyzstan"},
                "Kirghiz": {"numeric": "417", "alpha_2": "KG", "alpha_3": "KGZ", "country": "Kyrgyzstan"},
                "Lao": {"numeric": "418", "alpha_2": "LA", "alpha_3": "LAO",
                        "country": "Lao People's Democratic Republic"},
                "Laotian": {"numeric": "418", "alpha_2": "LA", "alpha_3": "LAO",
                            "country": "Lao People's Democratic Republic"},
                "Latvian": {"numeric": "428", "alpha_2": "LV", "alpha_3": "LVA", "country": "Latvia"},
                "Lebanese": {"numeric": "422", "alpha_2": "LB", "alpha_3": "LBN", "country": "Lebanon"},
                "Basotho": {"numeric": "426", "alpha_2": "LS", "alpha_3": "LSO", "country": "Lesotho"},
                "Liberian": {"numeric": "430", "alpha_2": "LR", "alpha_3": "LBR", "country": "Liberia"},
                "Libyan": {"numeric": "434", "alpha_2": "LY", "alpha_3": "LBY", "country": "Libya"},
                "Liechtenstein": {"numeric": "438", "alpha_2": "LI", "alpha_3": "LIE", "country": "Liechtenstein"},
                "Lithuanian": {"numeric": "440", "alpha_2": "LT", "alpha_3": "LTU", "country": "Lithuania"},
                "Luxembourg": {"numeric": "442", "alpha_2": "LU", "alpha_3": "LUX", "country": "Luxembourg"},
                "Luxembourgish": {"numeric": "442", "alpha_2": "LU", "alpha_3": "LUX", "country": "Luxembourg"},
                "Macanese": {"numeric": "446", "alpha_2": "MO", "alpha_3": "MAC", "country": "Macao"},
                "Macedonian": {"numeric": "807", "alpha_2": "MK", "alpha_3": "MKD",
                               "country": "Macedonia, Republic of"},
                "Malagasy": {"numeric": "450", "alpha_2": "MG", "alpha_3": "MDG", "country": "Madagascar"},
                "Malawian": {"numeric": "454", "alpha_2": "MW", "alpha_3": "MWI", "country": "Malawi"},
                "Malaysian": {"numeric": "458", "alpha_2": "MY", "alpha_3": "MYS", "country": "Malaysia"},
                "Maldivian": {"numeric": "462", "alpha_2": "MV", "alpha_3": "MDV", "country": "Maldives"},
                "Malian": {"numeric": "466", "alpha_2": "ML", "alpha_3": "MLI", "country": "Mali"},
                "Malinese": {"numeric": "466", "alpha_2": "ML", "alpha_3": "MLI", "country": "Mali"},
                "Maltese": {"numeric": "470", "alpha_2": "MT", "alpha_3": "MLT", "country": "Malta"},
                "Marshallese": {"numeric": "584", "alpha_2": "MH", "alpha_3": "MHL", "country": "Marshall Islands"},
                "Martiniquais": {"numeric": "474", "alpha_2": "MQ", "alpha_3": "MTQ", "country": "Martinique"},
                "Martinican": {"numeric": "474", "alpha_2": "MQ", "alpha_3": "MTQ", "country": "Martinique"},
                "Mauritanian": {"numeric": "478", "alpha_2": "MR", "alpha_3": "MRT", "country": "Mauritania"},
                "Mauritian": {"numeric": "480", "alpha_2": "MU", "alpha_3": "MUS", "country": "Mauritius"},
                "Mahoran": {"numeric": "175", "alpha_2": "YT", "alpha_3": "MYT", "country": "Mayotte"},
                "Mexican": {"numeric": "484", "alpha_2": "MX", "alpha_3": "MEX", "country": "Mexico"},
                "Micronesian": {"numeric": "583", "alpha_2": "FM", "alpha_3": "FSM",
                                "country": "Micronesia, Federated States of"},
                "Moldovan": {"numeric": "498", "alpha_2": "MD", "alpha_3": "MDA", "country": "Moldova, Republic of"},
                "Monégasque": {"numeric": "492", "alpha_2": "MC", "alpha_3": "MCO", "country": "Monaco"},
                "Monacan": {"numeric": "492", "alpha_2": "MC", "alpha_3": "MCO", "country": "Monaco"},
                "Mongolian": {"numeric": "496", "alpha_2": "MN", "alpha_3": "MNG", "country": "Mongolia"},
                "Montenegrin": {"numeric": "499", "alpha_2": "ME", "alpha_3": "MNE", "country": "Montenegro"},
                "Montserratian": {"numeric": "500", "alpha_2": "MS", "alpha_3": "MSR", "country": "Montserrat"},
                "Moroccan": {"numeric": "504", "alpha_2": "MA", "alpha_3": "MAR", "country": "Morocco"},
                "Mozambican": {"numeric": "508", "alpha_2": "MZ", "alpha_3": "MOZ", "country": "Mozambique"},
                "Burmese": {"numeric": "104", "alpha_2": "MM", "alpha_3": "MMR", "country": "Myanmar"},
                "Namibian": {"numeric": "516", "alpha_2": "NA", "alpha_3": "NAM", "country": "Namibia"},
                "Nauruan": {"numeric": "520", "alpha_2": "NR", "alpha_3": "NRU", "country": "Nauru"},
                "Nepali": {"numeric": "524", "alpha_2": "NP", "alpha_3": "NPL", "country": "Nepal"},
                "Nepalese": {"numeric": "524", "alpha_2": "NP", "alpha_3": "NPL", "country": "Nepal"},
                "Dutch": {"numeric": "528", "alpha_2": "NL", "alpha_3": "NLD", "country": "Netherlands"},
                "Netherlandic": {"numeric": "528", "alpha_2": "NL", "alpha_3": "NLD", "country": "Netherlands"},
                "New Caledonian": {"numeric": "540", "alpha_2": "NC", "alpha_3": "NCL", "country": "New Caledonia"},
                "New Zealand": {"numeric": "554", "alpha_2": "NZ", "alpha_3": "NZL", "country": "New Zealand"},
                "NZ": {"numeric": "554", "alpha_2": "NZ", "alpha_3": "NZL", "country": "New Zealand"},
                "Nicaraguan": {"numeric": "558", "alpha_2": "NI", "alpha_3": "NIC", "country": "Nicaragua"},
                "Nigerien": {"numeric": "562", "alpha_2": "NE", "alpha_3": "NER", "country": "Niger"},
                "Nigerian": {"numeric": "566", "alpha_2": "NG", "alpha_3": "NGA", "country": "Nigeria"},
                "Niuean": {"numeric": "570", "alpha_2": "NU", "alpha_3": "NIU", "country": "Niue"},
                "Norfolk Island": {"numeric": "574", "alpha_2": "NF", "alpha_3": "NFK", "country": "Norfolk Island"},
                "Northern Marianan": {"numeric": "580", "alpha_2": "MP", "alpha_3": "MNP",
                                      "country": "Northern Mariana Islands"},
                "Norwegian": {"numeric": "578", "alpha_2": "NO", "alpha_3": "NOR", "country": "Norway"},
                "Omani": {"numeric": "512", "alpha_2": "OM", "alpha_3": "OMN", "country": "Oman"},
                "Pakistani": {"numeric": "586", "alpha_2": "PK", "alpha_3": "PAK", "country": "Pakistan"},
                "Palauan": {"numeric": "585", "alpha_2": "PW", "alpha_3": "PLW", "country": "Palau"},
                "Palestinian": {"numeric": "275", "alpha_2": "PS", "alpha_3": "PSE", "country": "Palestine, State of"},
                "Panamanian": {"numeric": "591", "alpha_2": "PA", "alpha_3": "PAN", "country": "Panama"},
                "Papua New Guinean": {"numeric": "598", "alpha_2": "PG", "alpha_3": "PNG",
                                      "country": "Papua New Guinea"},
                "Papuan": {"numeric": "598", "alpha_2": "PG", "alpha_3": "PNG", "country": "Papua New Guinea"},
                "Paraguayan": {"numeric": "600", "alpha_2": "PY", "alpha_3": "PRY", "country": "Paraguay"},
                "Peruvian": {"numeric": "604", "alpha_2": "PE", "alpha_3": "PER", "country": "Peru"},
                "Philippine": {"numeric": "608", "alpha_2": "PH", "alpha_3": "PHL", "country": "Philippines"},
                "Filipino": {"numeric": "608", "alpha_2": "PH", "alpha_3": "PHL", "country": "Philippines"},
                "Pitcairn Island": {"numeric": "612", "alpha_2": "PN", "alpha_3": "PCN", "country": "Pitcairn"},
                "Polish": {"numeric": "616", "alpha_2": "PL", "alpha_3": "POL", "country": "Poland"},
                "Portuguese": {"numeric": "620", "alpha_2": "PT", "alpha_3": "PRT", "country": "Portugal"},
                "Puerto Rican": {"numeric": "630", "alpha_2": "PR", "alpha_3": "PRI", "country": "Puerto Rico"},
                "Qatari": {"numeric": "634", "alpha_2": "QA", "alpha_3": "QAT", "country": "Qatar"},
                "Réunionese": {"numeric": "638", "alpha_2": "RE", "alpha_3": "REU", "country": "Réunion"},
                "Réunionnais": {"numeric": "638", "alpha_2": "RE", "alpha_3": "REU", "country": "Réunion"},
                "Romanian": {"numeric": "642", "alpha_2": "RO", "alpha_3": "ROU", "country": "Romania"},
                "Russian": {"numeric": "643", "alpha_2": "RU", "alpha_3": "RUS", "country": "Russian Federation"},
                "Rwandan": {"numeric": "646", "alpha_2": "RW", "alpha_3": "RWA", "country": "Rwanda"},
                "Barthélemois": {"numeric": "652", "alpha_2": "BL", "alpha_3": "BLM", "country": "Saint Barthélemy"},
                "Saint Helenian": {"numeric": "654", "alpha_2": "SH", "alpha_3": "SHN",
                                   "country": "Saint Helena, Ascension and Tristan da Cunha"},
                "Kittitian": {"numeric": "659", "alpha_2": "KN", "alpha_3": "KNA", "country": "Saint Kitts and Nevis"},
                "Nevisian": {"numeric": "659", "alpha_2": "KN", "alpha_3": "KNA", "country": "Saint Kitts and Nevis"},
                "Saint Lucian": {"numeric": "662", "alpha_2": "LC", "alpha_3": "LCA", "country": "Saint Lucia"},
                "Saint-Martinoise": {"numeric": "663", "alpha_2": "MF", "alpha_3": "MAF",
                                     "country": "Saint Martin (French part)"},
                "Saint-Pierrais": {"numeric": "666", "alpha_2": "PM", "alpha_3": "SPM",
                                   "country": "Saint Pierre and Miquelon"},
                "Miquelonnais": {"numeric": "666", "alpha_2": "PM", "alpha_3": "SPM",
                                 "country": "Saint Pierre and Miquelon"},
                "Saint Vincentian": {"numeric": "670", "alpha_2": "VC", "alpha_3": "VCT",
                                     "country": "Saint Vincent and the Grenadines"},
                "Vincentian": {"numeric": "670", "alpha_2": "VC", "alpha_3": "VCT",
                               "country": "Saint Vincent and the Grenadines"},
                "Samoan": {"numeric": "882", "alpha_2": "WS", "alpha_3": "WSM", "country": "Samoa"},
                "Sammarinese": {"numeric": "674", "alpha_2": "SM", "alpha_3": "SMR", "country": "San Marino"},
                "São Toméan": {"numeric": "678", "alpha_2": "ST", "alpha_3": "STP", "country": "Sao Tome and Principe"},
                "Saudi": {"numeric": "682", "alpha_2": "SA", "alpha_3": "SAU", "country": "Saudi Arabia"},
                "Saudi Arabian": {"numeric": "682", "alpha_2": "SA", "alpha_3": "SAU", "country": "Saudi Arabia"},
                "Senegalese": {"numeric": "686", "alpha_2": "SN", "alpha_3": "SEN", "country": "Senegal"},
                "Serbian": {"numeric": "688", "alpha_2": "RS", "alpha_3": "SRB", "country": "Serbia"},
                "Seychellois": {"numeric": "690", "alpha_2": "SC", "alpha_3": "SYC", "country": "Seychelles"},
                "Sierra Leonean": {"numeric": "694", "alpha_2": "SL", "alpha_3": "SLE", "country": "Sierra Leone"},
                "Singaporean": {"numeric": "702", "alpha_2": "SG", "alpha_3": "SGP", "country": "Singapore"},
                "Sint Maarten": {"numeric": "534", "alpha_2": "SX", "alpha_3": "SXM",
                                 "country": "Sint Maarten (Dutch part)"},
                "Slovak": {"numeric": "703", "alpha_2": "SK", "alpha_3": "SVK", "country": "Slovakia"},
                "Slovenian": {"numeric": "705", "alpha_2": "SI", "alpha_3": "SVN", "country": "Slovenia"},
                "Slovene": {"numeric": "705", "alpha_2": "SI", "alpha_3": "SVN", "country": "Slovenia"},
                "Solomon Island": {"numeric": "90", "alpha_2": "SB", "alpha_3": "SLB", "country": "Solomon Islands"},
                "Somali": {"numeric": "706", "alpha_2": "SO", "alpha_3": "SOM", "country": "Somalia"},
                "Somalian": {"numeric": "706", "alpha_2": "SO", "alpha_3": "SOM", "country": "Somalia"},
                "South African": {"numeric": "710", "alpha_2": "ZA", "alpha_3": "ZAF", "country": "South Africa"},
                "South Georgian": {"numeric": "239", "alpha_2": "GS", "alpha_3": "SGS",
                                   "country": "South Georgia and the South Sandwich Islands"},
                "South Sandwich Island": {"numeric": "239", "alpha_2": "GS", "alpha_3": "SGS",
                                          "country": "South Georgia and the South Sandwich Islands"},
                "South Sudanese": {"numeric": "728", "alpha_2": "SS", "alpha_3": "SSD", "country": "South Sudan"},
                "Spanish": {"numeric": "724", "alpha_2": "ES", "alpha_3": "ESP", "country": "Spain"},
                "Sri Lankan": {"numeric": "144", "alpha_2": "LK", "alpha_3": "LKA", "country": "Sri Lanka"},
                "Sudanese": {"numeric": "729", "alpha_2": "SD", "alpha_3": "SDN", "country": "Sudan"},
                "Surinamese": {"numeric": "740", "alpha_2": "SR", "alpha_3": "SUR", "country": "Suriname"},
                "Svalbard": {"numeric": "744", "alpha_2": "SJ", "alpha_3": "SJM", "country": "Svalbard and Jan Mayen"},
                "Swazi": {"numeric": "748", "alpha_2": "SZ", "alpha_3": "SWZ", "country": "Swaziland"},
                "Swedish": {"numeric": "752", "alpha_2": "SE", "alpha_3": "SWE", "country": "Sweden"},
                "Swiss": {"numeric": "756", "alpha_2": "CH", "alpha_3": "CHE", "country": "Switzerland"},
                "Syrian": {"numeric": "760", "alpha_2": "SY", "alpha_3": "SYR", "country": "Syrian Arab Republic"},
                "Taiwanese": {"numeric": "158", "alpha_2": "TW", "alpha_3": "TWN",
                              "country": "Taiwan, Province of China"},
                "Tajikistani": {"numeric": "762", "alpha_2": "TJ", "alpha_3": "TJK", "country": "Tajikistan"},
                "Tanzanian": {"numeric": "834", "alpha_2": "TZ", "alpha_3": "TZA",
                              "country": "Tanzania, United Republic of"},
                "Thai": {"numeric": "764", "alpha_2": "TH", "alpha_3": "THA", "country": "Thailand"},
                "Timorese": {"numeric": "626", "alpha_2": "TL", "alpha_3": "TLS", "country": "Timor-Leste"},
                "Togolese": {"numeric": "768", "alpha_2": "TG", "alpha_3": "TGO", "country": "Togo"},
                "Tokelauan": {"numeric": "772", "alpha_2": "TK", "alpha_3": "TKL", "country": "Tokelau"},
                "Tongan": {"numeric": "776", "alpha_2": "TO", "alpha_3": "TON", "country": "Tonga"},
                "Trinidadian": {"numeric": "780", "alpha_2": "TT", "alpha_3": "TTO",
                                "country": "Trinidad and Tobago"},
                "Tobagonian": {"numeric": "780", "alpha_2": "TT", "alpha_3": "TTO",
                               "country": "Trinidad and Tobago"},
                "Tunisian": {"numeric": "788", "alpha_2": "TN", "alpha_3": "TUN", "country": "Tunisia"},
                "Turkish": {"numeric": "792", "alpha_2": "TR", "alpha_3": "TUR", "country": "Turkey"},
                "Turkmen": {"numeric": "795", "alpha_2": "TM", "alpha_3": "TKM", "country": "Turkmenistan"},
                "Turks and Caicos Island": {"numeric": "796", "alpha_2": "TC", "alpha_3": "TCA",
                                            "country": "Turks and Caicos Islands"},
                "Tuvaluan": {"numeric": "798", "alpha_2": "TV", "alpha_3": "TUV", "country": "Tuvalu"},
                "Ugandan": {"numeric": "800", "alpha_2": "UG", "alpha_3": "UGA", "country": "Uganda"},
                "Ukrainian": {"numeric": "804", "alpha_2": "UA", "alpha_3": "UKR", "country": "Ukraine"},
                "Emirati": {"numeric": "784", "alpha_2": "AE", "alpha_3": "ARE", "country": "United Arab Emirates"},
                "Emirian": {"numeric": "784", "alpha_2": "AE", "alpha_3": "ARE", "country": "United Arab Emirates"},
                "Emiri": {"numeric": "784", "alpha_2": "AE", "alpha_3": "ARE", "country": "United Arab Emirates"},
                "British": {"numeric": "826", "alpha_2": "GB", "alpha_3": "GBR",
                            "country": "United Kingdom"},
                "English": {"numeric": "826", "alpha_2": "GB", "alpha_3": "GBR",
                            "country": "United Kingdom"},
                "Scottish": {"numeric": "826", "alpha_2": "GB", "alpha_3": "GBR",
                             "country": "United Kingdom"},
                "Welsh": {"numeric": "826", "alpha_2": "GB", "alpha_3": "GBR",
                          "country": "United Kingdom"},
                "Northern Irish": {"numeric": "826", "alpha_2": "GB", "alpha_3": "GBR",
                                   "country": "United Kingdom"},
                "American": {"numeric": "840", "alpha_2": "US", "alpha_3": "USA",
                             "country": "United States"},
                "Uruguayan": {"numeric": "858", "alpha_2": "UY", "alpha_3": "URY", "country": "Uruguay"},
                "Uzbekistani": {"numeric": "860", "alpha_2": "UZ", "alpha_3": "UZB", "country": "Uzbekistan"},
                "Uzbek": {"numeric": "860", "alpha_2": "UZ", "alpha_3": "UZB", "country": "Uzbekistan"},
                "Ni-Vanuatu": {"numeric": "548", "alpha_2": "VU", "alpha_3": "VUT", "country": "Vanuatu"},
                "Vanuatuan": {"numeric": "548", "alpha_2": "VU", "alpha_3": "VUT", "country": "Vanuatu"},
                "Venezuelan": {"numeric": "862", "alpha_2": "VE", "alpha_3": "VEN",
                               "country": "Venezuela, Bolivarian Republic of"},
                "Vietnamese": {"numeric": "704", "alpha_2": "VN", "alpha_3": "VNM", "country": "Vietnam"},
                "Vietnam": {"numeric": "704", "alpha_2": "VN", "alpha_3": "VNM", "country": "Viet nam"},
                "British Virgin Island": {"numeric": "92", "alpha_2": "VG", "alpha_3": "VGB",
                                          "country": "Virgin Islands, British"},
                "U.S. Virgin Island": {"numeric": "850", "alpha_2": "VI", "alpha_3": "VIR",
                                       "country": "Virgin Islands, U.S."},
                "Wallis and Futuna": {"numeric": "876", "alpha_2": "WF", "alpha_3": "WLF",
                                      "country": "Wallis and Futuna"},
                "Wallisian": {"numeric": "876", "alpha_2": "WF", "alpha_3": "WLF", "country": "Wallis and Futuna"},
                "Futunan": {"numeric": "876", "alpha_2": "WF", "alpha_3": "WLF", "country": "Wallis and Futuna"},
                "Sahrawi": {"numeric": "732", "alpha_2": "EH", "alpha_3": "ESH", "country": "Western Sahara"},
                "Sahrawian": {"numeric": "732", "alpha_2": "EH", "alpha_3": "ESH", "country": "Western Sahara"},
                "Sahraouian": {"numeric": "732", "alpha_2": "EH", "alpha_3": "ESH", "country": "Western Sahara"},
                "Yemeni": {"numeric": "887", "alpha_2": "YE", "alpha_3": "YEM", "country": "Yemen"},
                "Zambian": {"numeric": "894", "alpha_2": "ZM", "alpha_3": "ZMB", "country": "Zambia"},
                "Zimbabwean": {"numeric": "716", "alpha_2": "ZW", "alpha_3": "ZWE", "country": "Zimbabwe"}}

# Check for subdivisions of these countries only
# Localize around Toronto
subdivision_list = ["CA", "US", "CN", "GB"] #, "GB"]

subdivision_conversion = {"BC": "CA-BC", "PEI": "CA-PE"}

major_city_list = {'Canada': ['Vancouver', 'Montreal', 'Ottawa', 'Toronto'],
                   'United States': ['New York', 'Chicago', 'Los Angeles', 'Miami', 'New York City', 'Houston'],
                   'China': ['Shanghai', 'Beijing', 'Tianjin', 'Shenzhen', 'Guangzhou', 'Wuhan', 'Chengdu', 'Xian', 'Nanjing', 'Chongquin', 'Hangzhou', 'Zhengzhou', 'Shenyang', 'Qingdao', 'Dalian', 'Suzhou', 'Harbin', 'Jinan', 'Changsha', 'Fuzhou', 'Shiziahuang', 'Nanning', 'Kunming', 'Changchun', 'Urumqi', 'Wuxi', 'Hefei', 'Changzhou', 'Taiyuan', 'Tangshan', 'Zibo', 'Guiyang', 'Xuzhou', 'Nanchang', 'Kowloon', 'Lanzhou'],
                   'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Hyderabad', 'Rawalpindi', 'Gujranwala'],
                   'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa'],
                   'Bangladesh': ['Dhaka', 'Chittagong'],
                   'Japan': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya'],
                   'Russia': ['Moscow', 'St Petersburg'],
                   'Philippines': ['Manila'],
                   'India': ['Mumbai', 'Bombay', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Ahmadabad', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Kanpur', 'Lucknow', 'Nagpur'],
                   'Brazil': ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte'],
                   'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu'],
                   'Congo D.R.': ['Kinshasa'],
                   'Peru': ['Lima'],
                   'Indonesia': ['Jakarta', 'Surabaya', 'Bandung'],
                   'Egypt': ['Cairo', 'Alexandria', 'Giza'],
                   'Mexico': ['Mexico City', 'Puebla'],
                   'Iran': ['Tehran', 'Mashhad', 'Isfahen'],
                   'Iraq': ['Baghdad', 'Basrah'],
                   'United Kingdom': ['London'],
                   'Vietnam': ['Ho Chi Minh City', 'Hanoi'],
                   'Thailand': ['Bangkok'],
                   'Colombia': ['Bogota', 'Medellin', 'Cali'],
                   'Nigeria': ['Lagos', 'Kano', 'Ibadan'],
                   'Saudi Arabia': ['Riyadh', 'Jeddah'],
                   'Chile': ['Santiago'],
                   'Singapore': ['Singapore'],
                   'Sudan': ['Khartoum', 'Omdurman'],
                   'Myanmar (Burma)': ['Yangon'],
                   'Morocco': ['Casablanca'],
                   'Australia': ['Sydney', 'Melbourne', 'Brisbane'],
                   'Ivory Coast': ['Abidjan'],
                   'Tanzania': ['Dar Es Salaam'],
                   'Jordan': ['Amman'],
                   'Afghanistan': ['Kabul'],
                   'Germany': ['Berlin'],
                   'Ecuador': ['Guayaquil', 'Quito'],
                   'Ethiopia': ['Addis Ababa'],
                   'Algeria': ['Algiers'],
                   'Spain': ['Madrid'],
                   'Kenya': ['Nairobi'],
                   'South Africa': ['Tshwane', 'Pretoria'],
                   'Argentina': ['Buenos Aires'],
                   'Ukraine': ['Kiev'],
                   'Italy': ['Rome'],
                   'Taiwan': ['Taipei', 'Kaohsiung', 'Taichung'],
                   'North Korea': ['Pyongyang'],
                   'Cameroon': ['Yaounde', 'Douala'],
                   'Uzbekistan': ['Tashkent'],
                   'Somalia': ['Mogadishu'],
                   'France': ['Paris'],
                   'Ghana': ['Accra'],
                   'Nicaragua': ['Managua'],
                   'Azerbaijan': ['Baku'],
                   'Guatemala': ['Guatamala City'],
                   'Angola': ['Luanda'],
                   'Romania': ['Bucharest']}

cities_near_orig = {"Canada": ["Barrie",
                               "Belleville",
                               "Brampton",
                               "Brant",
                               "Brantford",
                               "Brockville",
                               "Burlington",
                               "Cambridge",
                               "Clarence-Rockland",
                               "Cornwall",
                               "Dryden",
                               "Elliot Lake",
                               "Sudbury",
                               "Guelph",
                               "Haldimand County",
                               "Hamilton",
                               "Kawartha Lakes",
                               "Kenora",
                               "Kingston",
                               "Kitchener",
                               "London",
                               "Markham",
                               "Mississauga",
                               "Niagara Falls",
                               "Norfolk County",
                               "North Bay",
                               "Orillia",
                               "Oshawa",
                               "Ottawa",
                               "Owen Sound",
                               "Pembroke",
                               "Peterborough",
                               "Pickering",
                               "Port Colborne",
                               "Prince Edward County",
                               "Quinte West",
                               "Sarnia",
                               "Sault Ste. Marie",
                               "St. Catharines",
                               "St. Thomas",
                               "Stratford",
                               "Temiskaming Shores",
                               "Thorold",
                               "Thunder Bay",
                               "Timmins",
                               "Vaughan",
                               "Waterloo",
                               "Welland",
                               "Windsor",
                               "Woodstock"]}
